Repository elastic/synthetics, pull requests merged in 2020-11, with the labels that each got.

#127 Install alpha by default
  Dockerfile
Labels: bug

#128 Correction parse arg version for docker/bash.sh
  examples/docker/bash.sh
Labels: bug

#129 Report URL on errors
  __tests__/core/runner.test.ts
  src/core/runner.ts
Labels: bug

#135 Use tini init daemon (correctly) in Docker (#134)
  Dockerfile
Labels: bug

#138 Bump todos dep to use alpha6
  examples/todos/package.json
Labels: bug

#147 fix: sync browser version in docker and examples
  Dockerfile
  build-docker.sh
  examples/todos/package.json
  package.json
Labels: [zube]: In Review

#148 ci: run e2e tests
  .ci/Jenkinsfile
  __tests__/e2e/docker-compose.yml
  __tests__/e2e/scripts/setup.sh
  __tests__/e2e/scripts/test.sh
Labels: ci, team:automation
