Repository elastic/synthetics, pull requests merged in 2021-02, with the labels that each got.

#205 chore: upgrade deps and fix types
  package.json
  src/cli.ts
  src/common_types.ts
  src/parse_args.ts
Labels: technical debt

#219 [CI] add badge
  README.md
Labels: ci

#213 [CI] Automate release process
  .ci/Jenkinsfile
  CONTRIBUTING.md
Labels: ci, team:automation

#221 ci: use the releaseNotification step
  .ci/Jenkinsfile
Labels: ci
