Repository elastic/synthetics, pull requests merged in 2021-09, with the labels that each got.

#374 Capture and log page errors
  __tests__/plugins/browser-console.test.ts
  __tests__/reporters/__snapshots__/json.test.ts.snap
  __tests__/reporters/json.test.ts
  src/common_types.ts
  src/plugins/browser-console.ts
  src/reporters/json.ts
Labels: enhancement, 7.16-candidate

#379 Re-add support for suite params
  __tests__/cli.test.ts
  src/cli.ts
  src/common_types.ts
  src/parse_args.ts
Labels: bug

#380 Append Elastic/synthetics to UA string
  __tests__/core/gatherer.test.ts
  __tests__/core/runner.test.ts
  src/core/gatherer.ts
Labels: enhancement, 7.16-candidate

#382 [CI] use obltGitHubComments
  .ci/Jenkinsfile
Labels: Team:Automation
