Repository elastic/synthetics, pull requests merged in 2021-05, with the labels that each got.

#276 Document adding CAs in offline example
  examples/todos/Dockerfile
Labels: enhancement

#274 perf: use context isolation for inidividual journeys
  __tests__/core/browser-service.test.ts
  __tests__/core/gatherer.test.ts
  __tests__/core/runner.test.ts
  __tests__/plugins/browser-console.test.ts
  __tests__/plugins/network.test.ts
  __tests__/plugins/performance.test.ts
  __tests__/plugins/tracing.test.ts
  src/core/gatherer.ts
  src/core/runner.ts
Labels: enhancement

#279 Upgrade all deps
  package-lock.json
  package.json
Labels: bug

#273 fix: capture hook errors in base reporter
  __tests__/reporters/__snapshots__/base.test.ts.snap
  __tests__/reporters/base.test.ts
  src/reporters/base.ts
Labels: [zube]: In Review, bug
