Repository elastic/synthetics, pull requests merged in 2022-01, with the labels that each got.

#439 chore - prevent notification of successful e2e tests
  .ci/e2e-synthetics.groovy
Labels: Team:Uptime

#426 Fix do not read configuration files for inline journeys unless a --config parameter is passed
  __tests__/cli.test.ts
  src/cli.ts
Labels: v8.0.0, Team:Uptime

#444 chore: neutral naming for synthetics
  .ci/Jenkinsfile
  .ci/jobs/e2e-synthetics-mbp.yml
  .ci/jobs/e2e-synthetics-schedule.yml
  .ci/jobs/synthetic-monitoring.yml
  .ci/schedule.groovy
  CONTRIBUTING.md
  README.md
  __tests__/e2e/README.md
Labels: Team:Automation
