Repository elastic/synthetics, pull requests merged in 2022-07, with the labels that each got.

#556 Upgrade proxy agent
  package-lock.json
  package.json
  src/core/expect.ts
Labels: enhancement

#553 Fix for broken win push
  src/push/plugin.ts
Labels: bug

#559 feat: support private locations in dsl and push command arguments
  __tests__/core/runner.test.ts
  __tests__/push/monitor.test.ts
  __tests__/utils/test-config.ts
  src/cli.ts
  src/common_types.ts
  src/core/runner.ts
  src/dsl/monitor.ts
  src/options.ts
  src/push/monitor.ts
Labels: Team:Uptime
